CREATE TABLE IF NOT EXISTS stock_kline (
    code       VARCHAR(10)  NOT NULL,
    scale      VARCHAR(10)  NOT NULL,
    trade_date DATE         NOT NULL,
    type       VARCHAR(20)  NOT NULL DEFAULT 'stock',
    open       DOUBLE PRECISION,
    high       DOUBLE PRECISION,
    low        DOUBLE PRECISION,
    close      DOUBLE PRECISION,
    volume     BIGINT,
    amount     DOUBLE PRECISION,
    turnover   DOUBLE PRECISION,
    pct_change DOUBLE PRECISION,
    change_amt DOUBLE PRECISION,
    amplitude  DOUBLE PRECISION,
    created_at TIMESTAMP,
    PRIMARY KEY (code, scale, trade_date)
);

CREATE TABLE IF NOT EXISTS stock_info (
    code       VARCHAR(10)  PRIMARY KEY,
    name       VARCHAR(64),
    type       VARCHAR(10),
    market     VARCHAR(10),
    board      VARCHAR(10),
    industry   VARCHAR(64),
    trading_hours VARCHAR(50),
    is_active  BOOLEAN,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source        VARCHAR(32) NOT NULL DEFAULT 'shiChang-tracker',
    openid        VARCHAR(64),
    unionid       VARCHAR(64),
    session_key   VARCHAR(128),
    nickname      VARCHAR(64),
    avatar_url    VARCHAR(512),
    phone_enc     VARCHAR(128),
    status        INT DEFAULT 1,
    last_login_at TIMESTAMP,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    UNIQUE (source, openid)
);

CREATE TABLE IF NOT EXISTS concept_board (
    plate_code VARCHAR(20) PRIMARY KEY,
    plate_name VARCHAR(64),
    cid        INT,
    updated_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS concept_stock (
    plate_code VARCHAR(20) NOT NULL,
    stock_code VARCHAR(10) NOT NULL,
    PRIMARY KEY (plate_code, stock_code)
);

-- 新闻/公告统一存储。Go 侧 DDL 使用 TIMESTAMPTZ；H2 测试库不支持该别名（已验证 2.2.224/2.3.232），
-- 故用全称 TIMESTAMP WITH TIME ZONE，二者在 PostgreSQL 中语义完全一致。
CREATE TABLE IF NOT EXISTS news_feed (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code   VARCHAR(10),
    title        VARCHAR(512),
    summary      TEXT,
    url          VARCHAR(1024),
    source       VARCHAR(64),
    published_at TIMESTAMP WITH TIME ZONE
);
-- 去重索引：与 Go 侧 BatchSave 的 ON CONFLICT DO NOTHING 语义一致（同 stock_code+title+published_at 跳过）
CREATE UNIQUE INDEX IF NOT EXISTS uk_news_feed_dedup ON news_feed (stock_code, title, published_at);

-- 指数/行情实时快照（定时任务每 60s 覆盖刷新，仅存最新值）
CREATE TABLE IF NOT EXISTS quote_snapshot (
    code       VARCHAR(20) PRIMARY KEY,
    name       VARCHAR(64),
    price      NUMERIC(18,4),
    pct_change NUMERIC(10,2),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RSS 新闻源配置表：源列表走数据库（RssNewsScheduler 每分钟读取 enabled=true 的源拉取新闻）。
-- 生产 PostgreSQL 执行同份 DDL 见 scripts/rss_source.sql（含 COMMENT ON 中文注释）。
CREATE TABLE IF NOT EXISTS rss_source (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键（自增）
    name            VARCHAR(64)  NOT NULL,                                 -- 源名称（展示用，如“少数派”）
    url             VARCHAR(512) NOT NULL,                                 -- RSS/Atom feed 地址
    via_worker      BOOLEAN      NOT NULL DEFAULT FALSE,                   -- 是否走 Cloudflare Worker 转发（海外源=true）
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,                    -- 是否启用（false 则跳过，保留不删）
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,                   -- 软删除标记（true=已删，列表默认不展示）
    last_status     VARCHAR(16),                                           -- 最近一次拉取状态：ok / fail（null=未拉过）
    last_error      VARCHAR(512),                                          -- 最近一次拉取失败原因
    last_fetch_at   TIMESTAMP,                                             -- 最近一次拉取时间
    last_item_count INT                                                     -- 最近一次拉取解析条目数
);
-- URL 唯一索引：防止重复源（代码种子与手工插入都幂等）
CREATE UNIQUE INDEX IF NOT EXISTS uk_rss_source_url ON rss_source (url);

-- 用户点击/行为打点表（生产 PostgreSQL 同份 DDL 见 scripts/click_event.sql，含 COMMENT 中文注释）
CREATE TABLE IF NOT EXISTS click_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     VARCHAR(64)  NOT NULL,
    user_id      BIGINT,
    session_id   VARCHAR(64),
    event_type   VARCHAR(32),
    event_name   VARCHAR(128) NOT NULL,
    page         VARCHAR(128),
    target       VARCHAR(128),
    props        TEXT,
    duration_ms  INTEGER,
    client_ts    BIGINT,
    server_ts    TIMESTAMP WITH TIME ZONE DEFAULT now(),
    ip           VARCHAR(64),
    platform     VARCHAR(32),
    app_version  VARCHAR(32)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_click_event_event_id ON click_event (event_id);
CREATE INDEX IF NOT EXISTS idx_click_event_name_ts ON click_event (event_name, server_ts);
CREATE INDEX IF NOT EXISTS idx_click_event_user_ts ON click_event (user_id, server_ts);
CREATE INDEX IF NOT EXISTS idx_click_event_type_ts ON click_event (event_type, server_ts);
