CREATE TABLE IF NOT EXISTS stock_kline (
    code       VARCHAR(10)  NOT NULL,
    scale      VARCHAR(10)  NOT NULL,
    trade_date DATE         NOT NULL,
    open       DOUBLE PRECISION,
    high       DOUBLE PRECISION,
    low        DOUBLE PRECISION,
    close      DOUBLE PRECISION,
    volume     BIGINT,
    amount     DOUBLE PRECISION,
    turnover   DOUBLE PRECISION,
    pct_change DOUBLE PRECISION,
    change_amt DOUBLE PRECISION,
    amplitude  DOUBLE PRECISION,
    created_at TIMESTAMP,
    PRIMARY KEY (code, scale, trade_date)
);

CREATE TABLE IF NOT EXISTS stock_info (
    code       VARCHAR(10)  PRIMARY KEY,
    name       VARCHAR(64),
    type       VARCHAR(10),
    market     VARCHAR(10),
    board      VARCHAR(10),
    industry   VARCHAR(64),
    is_active  BOOLEAN,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openid        VARCHAR(64) UNIQUE,
    unionid       VARCHAR(64),
    session_key   VARCHAR(128),
    nickname      VARCHAR(64),
    avatar_url    VARCHAR(512),
    phone_enc     VARCHAR(128),
    status        INT DEFAULT 1,
    last_login_at TIMESTAMP,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS concept_board (
    plate_code VARCHAR(20) PRIMARY KEY,
    plate_name VARCHAR(64),
    cid        INT,
    updated_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS concept_stock (
    plate_code VARCHAR(20) NOT NULL,
    stock_code VARCHAR(10) NOT NULL,
    PRIMARY KEY (plate_code, stock_code)
);

-- 新闻/公告统一存储。Go 侧 DDL 使用 TIMESTAMPTZ；H2 测试库不支持该别名（已验证 2.2.224/2.3.232），
-- 故用全称 TIMESTAMP WITH TIME ZONE，二者在 PostgreSQL 中语义完全一致。
CREATE TABLE IF NOT EXISTS news_feed (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code   VARCHAR(10),
    title        VARCHAR(512),
    summary      TEXT,
    url          VARCHAR(1024),
    source       VARCHAR(64),
    published_at TIMESTAMP WITH TIME ZONE
);
-- 去重索引：与 Go 侧 BatchSave 的 ON CONFLICT DO NOTHING 语义一致（同 stock_code+title+published_at 跳过）
CREATE UNIQUE INDEX IF NOT EXISTS uk_news_feed_dedup ON news_feed (stock_code, title, published_at);
