/**
 * 图标素材路径映射 —— 由 front/scripts/fetch-icons.py 自动生成，请勿手改。
 * 重新生成：python front/scripts/fetch-icons.py（输出 static/icons/）
 */

/** 静态图标资源根目录（小程序本地路径） */
export const ICON_BASE = '/static/icons'

/** 行情 code → 图标图片路径（QUOTE_ICONS 全量，含金条/银条/公司 logo 覆盖） */
export const QUOTE_ICON_ASSETS: Record<string, string> = {
  '000660': '/static/icons/company/SK海力士.png',
  '005380': '/static/icons/company/现代汽车.png',
  '005930': '/static/icons/company/三星电子.png',
  '035420': '/static/icons/company/NAVER.png',
  '051910': '/static/icons/company/LG化学.png',
  '066570': '/static/icons/company/LG电子.png',
  '068270': '/static/icons/company/赛尔群.png',
  '373220': '/static/icons/company/LG新能源.png',
  '4063': '/static/icons/company/信越化学.png',
  '6758': '/static/icons/company/索尼.png',
  '6861': '/static/icons/company/基恩士.png',
  '6954': '/static/icons/company/发那科.png',
  '6981': '/static/icons/company/村田制作所.png',
  '7203': '/static/icons/company/丰田汽车.png',
  '7974': '/static/icons/company/任天堂.png',
  '8035': '/static/icons/company/东京电子.png',
  ALUMINUM: '/static/icons/emoji/1fa99.png',
  ANTIMONY: '/static/icons/emoji/1f9ea.png',
  AVG: '/static/icons/emoji/1f9ee.png',
  BK0438: '/static/icons/emoji/1f6d2.png',
  BK0464: '/static/icons/emoji/1f6e2.png',
  BK0475: '/static/icons/emoji/1f3e6.png',
  BK0478: '/static/icons/emoji/1f9f2.png',
  BK0490: '/static/icons/emoji/1f6e1.png',
  BK0493: '/static/icons/emoji/1f331.png',
  BK0547: '/static/icons/metal/gold-bar.png',
  BK0574: '/static/icons/emoji/1f50b.png',
  BK0577: '/static/icons/emoji/2622.png',
  BK0579: '/static/icons/emoji/2601.png',
  BK0588: '/static/icons/emoji/2600.png',
  BK0802: '/static/icons/emoji/1f697.png',
  BK0843: '/static/icons/emoji/26fd.png',
  BK0917: '/static/icons/emoji/1f52c.png',
  BK0921: '/static/icons/emoji/1f6f0.png',
  BK0922: '/static/icons/emoji/1f5c4.png',
  BK0963: '/static/icons/emoji/1f680.png',
  BK1016: '/static/icons/emoji/1f9ea.png',
  BK1090: '/static/icons/emoji/1f916.png',
  BK1128: '/static/icons/emoji/1f4a1.png',
  BK1134: '/static/icons/emoji/1f9e0.png',
  BK1137: '/static/icons/emoji/1f4be.png',
  BK1216: '/static/icons/emoji/1f48a.png',
  BK1647: '/static/icons/emoji/26a1.png',
  BRT: '/static/icons/emoji/1f6e2.png',
  CNYJPY: '/static/icons/emoji/1f4b1.png',
  CNYKRW: '/static/icons/emoji/1f4b1.png',
  COPPER: '/static/icons/emoji/1f527.png',
  GC: '/static/icons/metal/gold-bar.png',
  GERMANIUM: '/static/icons/emoji/1f48e.png',
  GOLD: '/static/icons/metal/gold-bar.png',
  HG: '/static/icons/emoji/2699.png',
  INDIUM: '/static/icons/emoji/1f4c0.png',
  KQ11: '/static/icons/emoji/1f1f0-1f1f7.png',
  KS11: '/static/icons/emoji/1f1f0-1f1f7.png',
  MOLY: '/static/icons/emoji/2692.png',
  N225: '/static/icons/emoji/1f1ef-1f1f5.png',
  NG: '/static/icons/emoji/1f525.png',
  NICKEL: '/static/icons/emoji/1f6e0.png',
  SENSEX: '/static/icons/emoji/1f1ee-1f1f3.png',
  SI: '/static/icons/metal/silver-bar.png',
  SILVER: '/static/icons/metal/silver-bar.png',
  SOX: '/static/icons/emoji/1f52c.png',
  TIN: '/static/icons/emoji/1f9f0.png',
  TLT: '/static/icons/emoji/1f4ca.png',
  TPX: '/static/icons/emoji/1f1ef-1f1f5.png',
  TUNGSTEN: '/static/icons/emoji/1f529.png',
  UDI: '/static/icons/emoji/1f4b5.png',
  USDCNY: '/static/icons/emoji/1f4b1.png',
  USDJPY: '/static/icons/emoji/1f4b1.png',
  USDKRW: '/static/icons/emoji/1f4b1.png',
  VIX: '/static/icons/emoji/1f4c9.png',
  VNINDEX: '/static/icons/emoji/1f1fb-1f1f3.png',
  ZINC: '/static/icons/emoji/2699.png',
  sh000001: '/static/icons/emoji/1f1e8-1f1f3.png',
  sh000688: '/static/icons/emoji/1f1e8-1f1f3.png',
  sz399001: '/static/icons/emoji/1f1e8-1f1f3.png',
  sz399006: '/static/icons/emoji/1f1e8-1f1f3.png',
  usDJI: '/static/icons/emoji/1f1fa-1f1f8.png',
  usINX: '/static/icons/emoji/1f1fa-1f1f8.png',
  usIXIC: '/static/icons/emoji/1f1fa-1f1f8.png',
}

/** 金店品牌 → 品牌 logo 图片路径（GOLD_SHOP_BRANDS，含占位图） */
export const GOLD_SHOP_ICON_ASSETS: Record<string, string> = {
  周大福: '/static/icons/brand/周大福.png',
  老凤祥: '/static/icons/brand/老凤祥.png',
  周六福: '/static/icons/brand/周六福.png',
  周生生: '/static/icons/brand/周生生.png',
  六福珠宝: '/static/icons/brand/六福珠宝.png',
  老庙: '/static/icons/brand/老庙.png',
  中国黄金: '/static/icons/brand/中国黄金.png',
  周大生: '/static/icons/brand/周大生.png',
  明牌珠宝: '/static/icons/brand/明牌珠宝.png',
  菜百: '/static/icons/brand/菜百.png',
  潮宏基: '/static/icons/brand/潮宏基.png',
  金至尊: '/static/icons/brand/金至尊.png',
  梦金园: '/static/icons/brand/梦金园.png',
  亚一金店: '/static/icons/brand/亚一金店.png',
  水贝黄金: '/static/icons/brand/水贝黄金.png',
}
