-- ============================================================
-- 前端展示配置表（app_config）
-- 用途：管理端通过 /api/mgr/configs 维护，小程序端按交付类型读取：
--   - cfg_type='login'    → 跟随登录接口 /api/v1/auth/login 下发（按端全局）
--   - cfg_type='display'  → 前端渲染时经 GET /api/v1/configs 读取
--   - cfg_type='other'    → 其他类型（可扩展枚举：Service 层加值即可，无需改表）
-- 两个正交维度：
--   - 结构轴 node_type：group（分组，可挂子项）/ item（配置项，有值）。
--     父子关系由 parent_id 表达；parent_id = NULL 且 node_type='item' 为“单独项”。
--   - 交付轴 cfg_type：见上（与结构轴正交：分组/单独项都可有任意 cfg_type）。
-- 分端：target = 'all'（全部端兜底）/ 具体 source（如 shiChang-tracker），
--       前端读取时先应用 all 再被具体端覆盖。
-- 说明：cfg_value 存 JSON 文本（TEXT 列，对齐 click_event.props 先例，保证 H2 测试同构）；
--       若将来需要 SQL 级 JSON 查询，可一行 ALTER：
--       ALTER TABLE app_config ALTER COLUMN cfg_value TYPE jsonb USING cfg_value::jsonb;
-- 兼容：PostgreSQL（与后端同库）
-- ============================================================
CREATE TABLE IF NOT EXISTS app_config (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键（自增）
    parent_id   BIGINT,                                               -- 父分组 id；NULL=顶层（单独项或顶级分组）
    node_type   VARCHAR(16) NOT NULL DEFAULT 'item',                  -- group=分组 / item=配置项
    cfg_type    VARCHAR(32) NOT NULL DEFAULT 'display',               -- login / display / other（交付类型）
    cfg_key     VARCHAR(64) NOT NULL,                                 -- 配置键：group 为嵌套容器键，item 为取值键
    cfg_value   TEXT,                                                 -- item 的 JSON 值（布尔/文本/对象）；group 为空
    remark      VARCHAR(255),                                         -- 说明（管理后台展示）
    target      VARCHAR(32) NOT NULL DEFAULT 'all',                   -- 分端：all / shiChang-tracker / hangQing-tracker
    sort        INT         NOT NULL DEFAULT 0,                       -- 排序，小值在前
    enabled     BOOLEAN     NOT NULL DEFAULT TRUE,                    -- 是否启用（false 则读取/下发时跳过）
    updated_at  TIMESTAMP   NOT NULL DEFAULT now()
);

-- 顶层（单独项/顶级分组）的 cfg_key 在同一端下唯一；分组下子项唯一性由 Service 层校验（体量小）
CREATE UNIQUE INDEX IF NOT EXISTS uk_app_config_top
    ON app_config (cfg_key, target) WHERE parent_id IS NULL;

-- 交付索引：按类型 + 端 + 启用读取（登录下发 / /api/v1/configs 共用）
CREATE INDEX IF NOT EXISTS idx_app_config_delivery
    ON app_config (cfg_type, target, enabled);

-- 表/列注释（psql \d+ 或 pgAdmin 可查看）
COMMENT ON TABLE  app_config            IS '前端展示配置表：结构轴(node_type+parent_id) × 交付轴(cfg_type)，按 target 分端';
COMMENT ON COLUMN app_config.id         IS '主键，自增';
COMMENT ON COLUMN app_config.parent_id  IS '父分组 id；NULL=顶层（单独项或顶级分组）';
COMMENT ON COLUMN app_config.node_type  IS '结构类型：group=分组（可挂子项）/ item=配置项（有值）';
COMMENT ON COLUMN app_config.cfg_type   IS '交付类型：login=跟随登录接口下发 / display=前端渲染读取 / other=其他（可扩展）';
COMMENT ON COLUMN app_config.cfg_key    IS '配置键：group 为嵌套容器键，item 为取值键；顶层在同端下唯一';
COMMENT ON COLUMN app_config.cfg_value  IS 'item 的 JSON 值（布尔/文本/对象），TEXT 存 JSON 文本；group 为空';
COMMENT ON COLUMN app_config.remark     IS '说明（管理后台展示用）';
COMMENT ON COLUMN app_config.target     IS '分端：all=全部端兜底 / 具体 source 覆盖';
COMMENT ON COLUMN app_config.sort       IS '排序，小值在前';
COMMENT ON COLUMN app_config.enabled    IS '是否启用（false 时读取/下发跳过）';
COMMENT ON COLUMN app_config.updated_at IS '最近更新时间';
