-- ============================================================
-- 用户点击/行为打点表
-- 用途：接收前端埋点批量上报（POST /api/v1/track/events），
--       记录用户用了什么功能（进页面、点击、搜索、切换主题、分享等）。
-- 兼容：PostgreSQL（与后端同库）
-- 执行：psql "postgresql://root:...@host:5432/gu_yu_stock" -f scripts/click_event.sql
-- 说明：
--   - event_id 唯一索引 + ON CONFLICT DO NOTHING：客户端断网重试/重复上报幂等，不重复计数；
--   - client_ts 为客户端事件时间(ms)，server_ts 为服务端接收时间（DEFAULT now()）；
--   - user_id 未登录为 NULL（匿名行为）；props 存 JSON 字符串，查询可用 props::jsonb。
--   - 生产库建议按时间分区 / 定期归档（数据随时间线性增长）。
-- ============================================================
CREATE TABLE IF NOT EXISTS click_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     VARCHAR(64)  NOT NULL,          -- 客户端幂等键（sessionId+序号），唯一去重
    user_id      BIGINT,                          -- users.id，未登录 NULL
    session_id   VARCHAR(64),                     -- 小程序一次启动一个会话
    event_type   VARCHAR(32),                     -- 事件大类：page_view/page_hide/tap/action
    event_name   VARCHAR(128) NOT NULL,           -- 点分事件名：search.submit 等
    page         VARCHAR(128),                    -- 触发页路由：pages/search/index
    target       VARCHAR(128),                    -- 目标：跳转页/标的 code/Tab 名
    props        TEXT,                            -- 扩展属性 JSON 字符串（keyword/theme 等）
    duration_ms  INTEGER,                         -- 停留时长（page_hide 类事件）
    client_ts    BIGINT,                          -- 客户端事件时间（毫秒）
    server_ts    TIMESTAMPTZ NOT NULL DEFAULT now(), -- 服务端接收时间
    ip           VARCHAR(64),
    platform     VARCHAR(32),                     -- devtools/ios/android
    app_version  VARCHAR(32)
);

-- 幂等去重唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS uk_click_event_event_id ON click_event (event_id);
-- 按事件名 / 时间查统计
CREATE INDEX IF NOT EXISTS idx_click_event_name_ts ON click_event (event_name, server_ts);
-- 按用户 / 时间查单个用户行为轨迹
CREATE INDEX IF NOT EXISTS idx_click_event_user_ts ON click_event (user_id, server_ts);
-- 按事件大类 / 时间做 PV 聚合
CREATE INDEX IF NOT EXISTS idx_click_event_type_ts ON click_event (event_type, server_ts);

-- 表/列注释（psql \d+ 或 pgAdmin 可查看）
COMMENT ON TABLE  click_event                IS '用户点击/行为打点表：前端埋点批量上报，记录用户使用了什么功能';
COMMENT ON COLUMN click_event.event_id       IS '客户端生成的幂等键（sessionId+自增序号），唯一索引去重';
COMMENT ON COLUMN click_event.user_id        IS '登录用户 id（users.id），匿名行为为 NULL';
COMMENT ON COLUMN click_event.session_id     IS '小程序一次启动的会话 id';
COMMENT ON COLUMN click_event.event_type     IS '事件大类：page_view / page_hide / tap / action';
COMMENT ON COLUMN click_event.event_name     IS '点分事件名，如 search.submit / theme.switch';
COMMENT ON COLUMN click_event.page           IS '触发页路由，如 pages/search/index';
COMMENT ON COLUMN click_event.target         IS '目标：跳转页 / 标的 code / Tab 名';
COMMENT ON COLUMN click_event.props          IS '扩展属性 JSON 字符串（keyword / theme 等），查询用 props::jsonb';
COMMENT ON COLUMN click_event.duration_ms    IS '页面停留时长（毫秒），page_hide 类事件填充';
COMMENT ON COLUMN click_event.client_ts      IS '客户端事件时间戳（毫秒）';
COMMENT ON COLUMN click_event.server_ts      IS '服务端接收时间（数据库默认 now()）';
