-- ============================================================
-- 前端公告内容表（notice）
-- 用途：管理端通过 /api/mgr/notices 维护，小程序端经 GET /api/v1/notices
--       按分端 + 展示位置 + 有效期读取“当前有效”的公告列表。
-- 说明：
--   - type 可扩展：notice（公告）/ banner（横幅）/ marquee（滚动）...
--   - target 分端：all=全部端 / 具体 source；position 展示位置（settings/home/...）
--   - 排序规则：pinned DESC, sort ASC（先置顶，再按权重；同权重按 created_at DESC 兜底）
--   - config 存 type 特有内容的 JSON 文本（content/icon/cover/link/subtitle...），
--     TEXT 列对齐 click_event.props 先例；如需 SQL 级 JSON 查询可 ALTER 为 jsonb。
-- 兼容：PostgreSQL（与后端同库）
-- ============================================================
CREATE TABLE IF NOT EXISTS notice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键（自增）
    type        VARCHAR(32) NOT NULL DEFAULT 'notice',                -- notice / banner / marquee（可扩展）
    title       VARCHAR(128),                                         -- 标题/管理端列表标签（可空）
    target      VARCHAR(32) NOT NULL DEFAULT 'all',                   -- 分端：all / shiChang-tracker / hangQing-tracker
    position    VARCHAR(32) NOT NULL DEFAULT 'settings',              -- 展示位置：settings / home / stock-detail ...
    sort        INT         NOT NULL DEFAULT 0,                       -- 组内排序，小值在前
    pinned      BOOLEAN     NOT NULL DEFAULT FALSE,                   -- 置顶：优先于 sort
    enabled     BOOLEAN     NOT NULL DEFAULT TRUE,                    -- 是否启用
    valid_from  TIMESTAMP,                                            -- 生效时间（空=立即）
    valid_to    TIMESTAMP,                                            -- 失效时间（空=长期）
    config      TEXT,                                                 -- type 特有内容 JSON（content/icon/cover/link/subtitle...）
    created_at  TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP   NOT NULL DEFAULT now()
);

-- 展示索引：分端 + 位置 + 启用 + 有效期（公开列表接口命中）
CREATE INDEX IF NOT EXISTS idx_notice_display
    ON notice (target, position, enabled, valid_from, valid_to);

-- 表/列注释（psql \d+ 或 pgAdmin 可查看）
COMMENT ON TABLE  notice            IS '前端公告内容表：分端 + 展示位置 + 有效期 + 置顶/排序';
COMMENT ON COLUMN notice.id         IS '主键，自增';
COMMENT ON COLUMN notice.type       IS '公告类型：notice=公告 / banner=横幅 / marquee=滚动（可扩展）';
COMMENT ON COLUMN notice.title      IS '标题/管理端列表标签（可空）';
COMMENT ON COLUMN notice.target     IS '分端：all=全部端 / 具体 source';
COMMENT ON COLUMN notice.position   IS '展示位置：settings / home / stock-detail ...';
COMMENT ON COLUMN notice.sort       IS '组内排序，小值在前';
COMMENT ON COLUMN notice.pinned     IS '置顶：true 时优先于 sort 排在最前';
COMMENT ON COLUMN notice.enabled    IS '是否启用（false 时不展示）';
COMMENT ON COLUMN notice.valid_from IS '生效时间（空=立即）';
COMMENT ON COLUMN notice.valid_to   IS '失效时间（空=长期）';
COMMENT ON COLUMN notice.config     IS 'type 特有内容 JSON 文本（content/icon/cover/link/subtitle...）';
COMMENT ON COLUMN notice.created_at IS '创建时间';
COMMENT ON COLUMN notice.updated_at IS '最近更新时间';
