-- ============================================================
-- RSS 新闻源配置表
-- 用途：RssNewsScheduler 每分钟从本表读取 enabled=true 的源拉取新闻。
--      源配置走数据库：增删改源只需操作本表，无需改配置/重启。
-- 说明：
--   - via_worker = true 的源走 Cloudflare Worker 转发（海外源）
--   - enabled = false 的源被跳过（保留不删）
--   - 表为空时，Java 启动会自动写入默认源（幂等，URL 唯一）
-- 兼容：PostgreSQL（与后端同库）
-- ============================================================
CREATE TABLE IF NOT EXISTS rss_source (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键（自增）
    name        VARCHAR(64)  NOT NULL,                                 -- 源名称（展示用，如“少数派”）
    url         VARCHAR(512) NOT NULL,                                 -- RSS/Atom feed 地址
    via_worker  BOOLEAN      NOT NULL DEFAULT FALSE,                   -- 是否走 Cloudflare Worker 转发（海外源=true）
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE                     -- 是否启用（false 则跳过，保留不删）
);

-- URL 唯一索引：防止重复源（代码种子与手工插入都幂等）
CREATE UNIQUE INDEX IF NOT EXISTS uk_rss_source_url ON rss_source (url);

-- 表/列注释（psql \d+ 或 pgAdmin 可查看）
COMMENT ON TABLE  rss_source      IS 'RSS 新闻源配置表：RssNewsScheduler 每分钟读取 enabled=true 的源拉取新闻';
COMMENT ON COLUMN rss_source.id          IS '主键，自增';
COMMENT ON COLUMN rss_source.name        IS '源名称（如：少数派、Yahoo Finance）';
COMMENT ON COLUMN rss_source.url         IS 'RSS/Atom feed 地址';
COMMENT ON COLUMN rss_source.via_worker  IS '是否经 Cloudflare Worker 转发拉取（海外源 true，中文源 false）';
COMMENT ON COLUMN rss_source.enabled     IS '启用开关：false 时跳过该源（保留不删）';

-- ============================================================
-- 默认源种子（中文财经向，可选执行）
-- 幂等：uk_rss_source_url 唯一索引 + ON CONFLICT DO NOTHING，重复执行安全。
-- 说明：
--   - via_worker = FALSE 直连（本机实测可用）
--   - via_worker = TRUE  走 Cloudflare Worker（需配 app.rss.worker-base，未配置时跳过+打 warn）
--   - 联合早报/鉅亨/中央社/香港01 为官方文档记载地址，走 Worker 后建议实测确认
--   - 想替换旧源：先 DELETE FROM rss_source; 再执行本段（别删完不插，否则启动会种子回代码默认源）
-- ============================================================
INSERT INTO rss_source (name, url, via_worker) VALUES
    -- 直连：实测可用
    ('华尔街见闻',    'https://dedicated.wallstreetcn.com/rss.xml',         FALSE),
    ('中新网财经',    'https://www.chinanews.com.cn/rss/finance.xml',      FALSE),
    -- 海外中文：走 Cloudflare Worker
    ('BBC 中文',      'https://feeds.bbci.co.uk/zhongwen/simp/rss.xml',    TRUE),
    ('FT中文网',      'https://www.ftchinese.com/rss/news',                TRUE),
    ('Yahoo 香港财经', 'https://hk.finance.yahoo.com/rss/',                 TRUE),
    -- 待实测：官方地址，Worker 下建议验证
    ('联合早报·财经',  'https://www.zaobao.com/rss/%e8%b4%a2%e7%bb%8f',     TRUE),
    ('鉅亨網',        'https://news.cnyes.com/rss/',                       TRUE),
    ('中央社即時',     'https://www.cna.com.tw/rss/news/first.aspx',        TRUE),
    ('香港01·財經',   'https://www.hk01.com/rss/16',                        TRUE)
ON CONFLICT (url) DO NOTHING;

-- ============================================================
-- 补充：财联社电报 + 股票/研报类（RSSHub 公共实例 + CNBC 官方频道）
-- 说明：
--   - rsshub.app 为公共实例（海外），国内直连不稳/被墙 → via_worker=true 走 Cloudflare Worker
--   - 若自建 RSSHub（海外服务器 docker run -d -p 1200:1200 diygod/rsshub），
--     可把 url 换成自建地址并设 via_worker=false（自建实例还能配缓存，减少上游压力）
--   - CNBC 股市/经济为官方 RSS（直连实测 200，30 条），与 Top News 同一体系
--   - 金十数据(黄金/快讯)、生意社(期货/大宗商品) 的 RSSHub 路由路径需以
--     RSSHub 文档为准（本网络无法访问 docs.rsshub.app），未列入；自建后可在
--     http://<rsshub>/ 首页路由列表确认再插入
-- ============================================================
INSERT INTO rss_source (name, url, via_worker) VALUES
    -- RSSHub（财联社/研报/热帖/快讯）：走 Worker
    ('财联社电报',     'https://rsshub.app/cls/telegraph',             TRUE),
    ('东方财富研报',   'https://rsshub.app/eastmoney/report',          TRUE),
    ('雪球热帖',       'https://rsshub.app/xueqiu/hots',               TRUE),
    ('华尔街见闻快讯', 'https://rsshub.app/wallstreetcn/live',         TRUE),
    -- CNBC 官方频道（股市/经济）：直连实测可用
    ('CNBC 股市',      'https://www.cnbc.com/id/10000664/device/rss/rss.html',  FALSE),
    ('CNBC 经济',      'https://www.cnbc.com/id/20910258/device/rss/rss.html',  FALSE)
ON CONFLICT (url) DO NOTHING;
