-- ============================================================
-- 微信接口凭证表（wx_access_token）
-- 用途：存储各端小程序的 access_token，由 RefreshWxAccessTokenTask 每 20 分钟刷新，
--       PullWxAdDataTask 直接从本表取最新 token 调用 publisher/stat，不自行换取。
--   - 每端（source）一行；secret 不落库，仍从 app.wechat.apps.<source>.appSecret 读。
--   - 微信 token 有效期 7200s；RefreshWxAccessTokenTask 每 20 分钟刷新一次，始终早于过期。
-- 兼容：PostgreSQL（与后端同库）
-- ============================================================
CREATE TABLE IF NOT EXISTS wx_access_token (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target       VARCHAR(32)  NOT NULL,                -- 端：app.wechat.apps 的 key（shiChang-tracker / ...）
    access_token VARCHAR(512) NOT NULL,                -- 微信 access_token
    expires_at   TIMESTAMP    NOT NULL,                -- 过期时间（换得时间 + expires_in）
    refreshed_at TIMESTAMP    NOT NULL DEFAULT now(),  -- 最近一次刷新时间
    created_at   TIMESTAMP    NOT NULL DEFAULT now()
);

-- 每端一行，刷新时 upsert 覆盖
CREATE UNIQUE INDEX IF NOT EXISTS uk_wx_access_token
    ON wx_access_token (target);

COMMENT ON TABLE  wx_access_token              IS '微信接口凭证：每端一条，RefreshWxAccessTokenTask 每 20 分钟刷新';
COMMENT ON COLUMN wx_access_token.target       IS '端：app.wechat.apps 的 key（如 shiChang-tracker）';
COMMENT ON COLUMN wx_access_token.access_token IS '微信 access_token';
COMMENT ON COLUMN wx_access_token.expires_at   IS 'token 过期时间（= 换得时间 + expires_in）';
COMMENT ON COLUMN wx_access_token.refreshed_at IS '最近一次刷新时间';
