-- ============================================================
-- 微信广告日统计表（wx_ad_daily_stat）
-- 用途：PullWxAdDataTask 每日（9~17 点每 20 分钟）拉取 publisher_adpos_general 落库，
--       一行 = target(端) × ad_slot(广告位类型) × stat_date(统计日)。
-- 只存广告数据：拉取量 / 曝光 / 点击 / 收入等指标，不存任务日志/字典/结算。
-- 金额单位：income 一律为"分"；ecpm 为"分/千次曝光"。
-- 幂等：以 (target, stat_date, ad_slot) 为业务键 upsert（见唯一索引），重复拉取即覆盖。
-- 兼容：PostgreSQL（与后端同库）
-- ============================================================
CREATE TABLE IF NOT EXISTS wx_ad_daily_stat (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target         VARCHAR(32)  NOT NULL,              -- 端：app.wechat.apps 的 key（shiChang-tracker / ...）
    stat_date      DATE         NOT NULL,              -- 统计日期（微信侧 date 字段）
    slot_id        BIGINT,                             -- 广告位类型数字 id（raw 保留，可空）
    ad_slot        VARCHAR(40)  NOT NULL,              -- 广告位类型枚举：SLOT_ID_WEAPP_COVER / ...
    ad_slot_name   VARCHAR(32),                        -- 广告位类型中文名：封面广告 / ...（代码内枚举映射填值）
    req_succ_count BIGINT       NOT NULL DEFAULT 0,    -- 拉取量（请求成功数）
    exposure_count BIGINT       NOT NULL DEFAULT 0,    -- 曝光量
    exposure_rate  NUMERIC(18,9) NOT NULL DEFAULT 0,   -- 曝光率（0~1）
    click_count    BIGINT       NOT NULL DEFAULT 0,    -- 点击量
    click_rate     NUMERIC(18,9) NOT NULL DEFAULT 0,   -- 点击率（0~1）
    income_fen     BIGINT       NOT NULL DEFAULT 0,    -- 分账收入（分）
    ecpm_fen       NUMERIC(18,9) NOT NULL DEFAULT 0,   -- 千次曝光收益（分/千次）
    pulled_at      TIMESTAMP    NOT NULL DEFAULT now(), -- 本行最近一次被拉取写入的时间
    created_at     TIMESTAMP    NOT NULL DEFAULT now()
);

-- 业务唯一键：同一端同一天同一广告位类型唯一（支持 upsert 幂等）
CREATE UNIQUE INDEX IF NOT EXISTS uk_wx_ad_daily_stat
    ON wx_ad_daily_stat (target, stat_date, ad_slot);

-- 按天看趋势
CREATE INDEX IF NOT EXISTS idx_wx_ad_daily_date
    ON wx_ad_daily_stat (target, stat_date);

COMMENT ON TABLE  wx_ad_daily_stat              IS '微信广告日统计（汇总）：广告位类型 × 天，只存拉取/曝光/点击/收入指标';
COMMENT ON COLUMN wx_ad_daily_stat.target       IS '端：app.wechat.apps 的 key（如 shiChang-tracker）';
COMMENT ON COLUMN wx_ad_daily_stat.ad_slot      IS '广告位类型枚举（SLOT_ID_WEAPP_COVER / ...）';
COMMENT ON COLUMN wx_ad_daily_stat.ad_slot_name IS '广告位类型中文名（封面广告 / ...），代码内枚举映射填值，微信侧不返回';
COMMENT ON COLUMN wx_ad_daily_stat.income_fen   IS '分账收入，单位：分';
COMMENT ON COLUMN wx_ad_daily_stat.ecpm_fen     IS '广告千次曝光收益，单位：分/千次曝光';
