-- ============================================================
-- 微信小程序访问趋势日统计表（wx_daily_visit_stat）
-- 用途：拉取微信「获取用户访问小程序数据日趋势」接口
--       （datacube/getweanalysisappiddailyvisittrend）落库，
--       一行 = target(端) × stat_date(统计日)。
-- 字段：打开次数/访问次数/访问人数(日活)/新用户数(日新增)/停留时长/访问深度。
-- 注意：微信该接口一次只能查 1 天，且 end_date 最大为昨日（不能查今天），
--       故只能逐日拉取前一天，历史数据需逐日补。
-- 幂等：以 (target, stat_date) 为业务键 upsert（见唯一索引）。
-- 兼容：PostgreSQL（与后端同库）
-- ============================================================
CREATE TABLE IF NOT EXISTS wx_daily_visit_stat (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target            VARCHAR(32)  NOT NULL,              -- 端：app.wechat.apps 的 key（shiChang-tracker / ...）
    stat_date         DATE         NOT NULL,              -- 统计日期（微信侧 ref_date 字段）
    session_cnt       BIGINT       NOT NULL DEFAULT 0,    -- 打开次数
    visit_pv          BIGINT       NOT NULL DEFAULT 0,    -- 访问次数
    visit_uv          BIGINT       NOT NULL DEFAULT 0,    -- 访问人数（日活）
    visit_uv_new      BIGINT       NOT NULL DEFAULT 0,    -- 新用户数（日新增）
    stay_time_uv      DOUBLE PRECISION,                   -- 人均停留时长（秒，浮点）
    stay_time_session DOUBLE PRECISION,                   -- 次均停留时长（秒，浮点）
    visit_depth       DOUBLE PRECISION,                   -- 平均访问深度（浮点）
    pulled_at         TIMESTAMP    NOT NULL DEFAULT now(), -- 本行最近一次被拉取写入的时间
    created_at        TIMESTAMP    NOT NULL DEFAULT now()
);

-- 业务唯一键：同一端同一天唯一（支持 upsert 幂等）
CREATE UNIQUE INDEX IF NOT EXISTS uk_wx_daily_visit_stat
    ON wx_daily_visit_stat (target, stat_date);

-- 按天看趋势
CREATE INDEX IF NOT EXISTS idx_wx_daily_visit_date
    ON wx_daily_visit_stat (target, stat_date);

COMMENT ON TABLE  wx_daily_visit_stat                  IS '微信小程序访问趋势日统计：打开次数/访问次数/日活(访问人数)/日新增(新用户数)/停留时长/访问深度';
COMMENT ON COLUMN wx_daily_visit_stat.id               IS '主键，自增';
COMMENT ON COLUMN wx_daily_visit_stat.target           IS '端：app.wechat.apps 的 key（如 shiChang-tracker）';
COMMENT ON COLUMN wx_daily_visit_stat.stat_date        IS '统计日期（微信侧 ref_date 字段）';
COMMENT ON COLUMN wx_daily_visit_stat.session_cnt      IS '打开次数';
COMMENT ON COLUMN wx_daily_visit_stat.visit_pv         IS '访问次数';
COMMENT ON COLUMN wx_daily_visit_stat.visit_uv         IS '访问人数（日活）';
COMMENT ON COLUMN wx_daily_visit_stat.visit_uv_new     IS '新用户数（日新增）';
COMMENT ON COLUMN wx_daily_visit_stat.stay_time_uv     IS '人均停留时长（秒，浮点）';
COMMENT ON COLUMN wx_daily_visit_stat.stay_time_session IS '次均停留时长（秒，浮点）';
COMMENT ON COLUMN wx_daily_visit_stat.visit_depth      IS '平均访问深度（浮点）';
COMMENT ON COLUMN wx_daily_visit_stat.pulled_at        IS '本行最近一次被拉取写入的时间';
COMMENT ON COLUMN wx_daily_visit_stat.created_at       IS '创建时间';
